version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: stock-screener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: januloka
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres

volumes:
  pgdata:
