FROM python:3.11-slim

WORKDIR /app


RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    g++ \
    curl \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Ta-lib
RUN wget -q http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz \
 && tar -xzf ta-lib-0.4.0-src.tar.gz \
 && cd ta-lib && ./configure --prefix=/usr && make && make install \
 && cd .. && rm -rf ta-lib ta-lib-0.4.0-src.tar.gz


COPY requirements.txt ./requirements.txt

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY .env .env

COPY . .

# Declare PYTHONPATH as a build-time arg so expanders like linters won't flag it as undefined
ARG PYTHONPATH=""
ENV PYTHONPATH="${PYTHONPATH}:/app"
ENV FLASK_APP=main.py

EXPOSE 8081
CMD ["uvicorn", "main:app","--port","8081","--host","0.0.0.0"]